version: '3'

services:
  node:
    container_name: ${DOCKER_PROJECT_NAME}_node
    image: node:20-alpine3.17
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: /bin/sh -c "npm install && npm run build"
